// Generated by tools/specs/generate_contracts.py. Do not edit.
export type CombatAction = { id: string; type: string; card_id: string | null; combat_card_index: string | null; target_combat_id: string | null; cost: number | null; choice_id: string | null; selection: string[] };
export type TraceStep = { action: CombatAction; state_hash: string; hp_loss: number };
export type SolveResult = { catalog_sha256: string; catalog_game_version: string; setup_hash: string; policy: "minimize_hp_loss"; won: boolean; complete: boolean; optimality_proven: boolean; hp_loss: number | null; final_hp: number | null; actions: TraceStep[]; action_ids: string[]; explored_states: number; cache_hits: number; runtime_seconds: number; termination_reason: string };
export type PackageIdentity = { package_id: string; sha256: string };
export type ContentCard = { id: string; name: string; character: string | null; card_type: string | null; cost: number; asset: string | null };
export type ContentCharacter = { id: string; name: string; max_hp: number; max_energy: number; starter_deck: Array<{ id: string; quantity: number; upgrade_level: number }>; starter_relics: string[]; asset: string | null };
export type ContentEnemy = { id: string; name: string; hp: [number, number]; ascension_hp: [number, number]; asset: string | null };
export type ContentManifest = { schema_version: 1; package: PackageIdentity; game_version: string; characters: ContentCharacter[]; cards: ContentCard[]; enemies: ContentEnemy[]; relics: Array<{ id: string; name: string; asset: string | null }> };
export type CombatSetupV2 = { schema_version: 2; package: PackageIdentity; ascension_level: number; rng: { run_seed: string; profile: string }; character: { id: string; current_hp: number; max_hp: number }; deck: Array<{ id: string; quantity: number; upgrade_level: number }>; relics: Array<{ id: string }>; potions: never[]; encounter: { type: "custom"; enemies: Array<{ id: string; current_hp: number; max_hp: number }> } };
export type BrowserSolveResult = { schema_version: 1; result: SolveResult; opening_hand: string[] };
