[package]
name = "rusty-spire-simulator"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rusty-spire-core = { path = "../rusty-spire-core" }
rusty-spire-data = { path = "../rusty-spire-data" }
rusty-spire-combat = { path = "../rusty-spire-combat" }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
